#ifndef SYS_SHM_LIST_H
#define SYS_SHM_LIST_H

#define SYS_SHM_LIST_RESNAME_SIZE   32
#define SYS_SHM_SECTOR_SIZE         16
#define SYS_SHM_LIST_SECTOR_SIZE    1
#define SYS_SHM_LIST_RESSIZE_SIZE   2
#define SYS_SHM_LIST_SEMCNT_SIZE    1
#define SYS_SHM_LIST_SEMOFFSET_SIZE 2
#define SYS_SHM_LIST_RES_SIZE (SYS_SHM_LIST_RESNAME_SIZE + SYS_SHM_LIST_RESSIZE_SIZE + SYS_SHM_LIST_SECTOR_SIZE)
#define SYS_SHM_LIST_NAME   "SYS_SHM_LIST"
#define SYS_SEMAPHORES_NAME "SYS_SEMAPHORES"
#define SYS_SHM_FILE_DESCRIPTOR_FOLDER  "/tmp/sys_shm/keys"

#endif // SYS_SHM_LIST_H
